-- MySQL Script generated by MySQL Workbench
-- Sat Feb 20 16:13:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pos` DEFAULT CHARACTER SET utf8 ;
USE `db_pos` ;

-- -----------------------------------------------------
-- Table `db_pos`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `categoriacol` VARCHAR(45) NOT NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `stock_disponible` INT NOT NULL,
  `stock_comprometido` INT NOT NULL,
  `stock_total` INT NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `imagen` VARCHAR(50) NULL,
  `estado` VARCHAR(20) NOT NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_categoria_idx` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `db_pos`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `tipo_persona` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NULL,
  `num_documento` VARCHAR(15) NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`pedido` (
  `idpedido` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `tipo_comprobante` VARCHAR(45) NOT NULL,
  `serie_comprobante` VARCHAR(45) NULL,
  `num_comprobante` VARCHAR(45) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `impuesto` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(45) NULL,
  `condicion` TINYINT NULL,
  `tipo_pedido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_persona_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_persona`
    FOREIGN KEY (`idcliente`)
    REFERENCES `db_pos`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`detalle_pedido` (
  `iddetalle_pedido` INT NOT NULL,
  `idpedido` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_compra` DECIMAL(11,2) NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `detalle_pedidocol` VARCHAR(45) NULL,
  PRIMARY KEY (`iddetalle_pedido`),
  INDEX `fk_detalle_pedido_idx` (`idpedido` ASC) VISIBLE,
  INDEX `fk_detalle_producto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_pedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `db_pos`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_pos`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(7) NULL,
  `num_comprobante` VARCHAR(10) NULL,
  `fecha_hora` DATETIME NULL,
  `impuesto` DECIMAL(10,2) NULL,
  `total_venta` DECIMAL(11,2) NULL,
  `estado` VARCHAR(20) NULL,
  `condicion` TINYINT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_venta_cliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `db_pos`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`receta` (
  `idreceta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idproducto` INT NOT NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idreceta`),
  INDEX `fk_receta_productoterminado_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_receta_productoterminado`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_pos`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`detalle_receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`detalle_receta` (
  `iddetalle_receta` INT NOT NULL AUTO_INCREMENT,
  `idreceta` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NULL,
  `costo_linea` DECIMAL(10,2) NOT NULL,
  `costo_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`iddetalle_receta`),
  INDEX `fk_detallereceta_receta_idx` (`idreceta` ASC) VISIBLE,
  INDEX `fk_detallereceta_producto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_detallereceta_receta`
    FOREIGN KEY (`idreceta`)
    REFERENCES `db_pos`.`receta` (`idreceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallereceta_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_pos`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`orden_produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`orden_produccion` (
  `idorden_produccion` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `cantidad_a_producir` DECIMAL(10,2) NOT NULL,
  `cantidad_producida` DECIMAL(10,2) NOT NULL,
  `cantidad_por_despachar` DECIMAL(10,2) NOT NULL,
  `costo_total` DECIMAL(10,2) NOT NULL,
  `costo_unitario` DECIMAL(10,2) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_cierre` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorden_produccion`),
  INDEX `fk_orden_produccion_producto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_orden_produccion_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_pos`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`despachos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`despachos` (
  `iddespacho` INT NOT NULL,
  `idorden_produccion` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `fecha_hora` VARCHAR(45) NULL,
  `condicion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddespacho`),
  INDEX `fk_despacho_op_idx` (`idorden_produccion` ASC) VISIBLE,
  CONSTRAINT `fk_despacho_op`
    FOREIGN KEY (`idorden_produccion`)
    REFERENCES `db_pos`.`orden_produccion` (`idorden_produccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`bodega` (
  `idbodega` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idbodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`movimiento_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`movimiento_producto` (
  `idmovimiento_producto` INT NOT NULL AUTO_INCREMENT,
  `idbodega` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `tipo_movimiento` VARCHAR(10) NOT NULL,
  `condicion` TINYINT NOT NULL,
  `id_despacho` INT NULL,
  PRIMARY KEY (`idmovimiento_producto`),
  INDEX `fk_movimiento_bodega_idx` (`idbodega` ASC) VISIBLE,
  INDEX `fk_movimiento_producto_idx` (`idproducto` ASC) VISIBLE,
  INDEX `fk_movimiento_despacho_idx` (`id_despacho` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_bodega`
    FOREIGN KEY (`idbodega`)
    REFERENCES `db_pos`.`bodega` (`idbodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_pos`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_despacho`
    FOREIGN KEY (`id_despacho`)
    REFERENCES `db_pos`.`despachos` (`iddespacho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pos`.`stock_bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pos`.`stock_bodega` (
  `idstock_bodega` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `idbodega` INT NOT NULL,
  `stock_disponible` DECIMAL(10,2) NOT NULL,
  `stock_comprometido` DECIMAL(10,2) NOT NULL,
  `stock_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idstock_bodega`),
  INDEX `fk_stockbodega_producto_idx` (`idproducto` ASC) VISIBLE,
  INDEX `fk_stockbodega_bodega_idx` (`idbodega` ASC) VISIBLE,
  CONSTRAINT `fk_stockbodega_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_pos`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stockbodega_bodega`
    FOREIGN KEY (`idbodega`)
    REFERENCES `db_pos`.`bodega` (`idbodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
